# Generated by Django 4.0.3 on 2022-04-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokedex',
            new_name='Pokemon',
        ),
    ]
